### ISSUE TITLE
Document addons

### ISSUE THREAD

**Issue by maciaszczykm** [loodse/docs#180]

**Comment by maciaszczykm** [comment]
/assign

Covered it while addon config docs.

**Comment by toschneck** [comment]
@maciaszczykm can you please also document, how the `addon variables` could be used inside of the add-on implementation.Are the handed is environment variables or how can I access the value?
https://docs.loodse.com/kubermatic/master/advanced/addons/#configuration-1

We also should describe a little bit more how the template variables are working https://docs.loodse.com/kubermatic/master/advanced/addons/#template-variables. As end user I would like to see an example how I can extract e.g. from a cluster object the values and use it in a template. Currently it's an guessing what could be used and what not.
