### ISSUE TITLE
Custom Links page has 404 link

### ISSUE THREAD

**Issue by thz** [loodse/docs#211]
found at:
https://docs.kubermatic.io/kubermatic/v2.12/advanced/custom_links/

"Check the [**Creating the Master Cluster**] values.yaml"

That link points to: https://docs.kubermatic.io/installation/install_kubermatic/_manual/#creating-the-master-cluster-values-yaml
... which goes 404.

**Comment by themue** [comment]
Link has to contain product and version. Will change.

https://docs.loodse.com/kubermatic/v2.12/installation/install_kubermatic/_manual/#creating-the-master-cluster-values-yaml

**Comment by themue** [comment]
PR is https://github.com/loodse/docs/pull/224

**Comment by scheeles** [comment]
New PR is https://github.com/loodse/docs/pull/226
